# Generated by Django 4.2.21 on 2025-05-30 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_shopee_remove_order_items_remove_order_user_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Shopee',
            new_name='Shop',
        ),
    ]
