# Generated by Django 5.2.1 on 2025-06-09 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_product_on_sale'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('average_rating', models.FloatField(default=0.0)),
                ('total_reviews', models.PositiveIntegerField(default=0)),
                ('shop', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='main.shop')),
            ],
        ),
    ]
